apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami-1
  template:
    metadata:
      labels:
        app: whoami-1
    spec:
      containers:
        - name: web
          image: kiamol/ch02-whoami
